server:
  host: "localhost"
  dbname: "defaultdb"
  port: 50051
  timeout: 3

wal:
  datadir: "./data"
  useS3: false
  s3Config:
    bucket: "my-wal-bucket"
    region: "us-east-1"
    accessKey: "your-access-key"
    secretKey: "your-secret-key"
